// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)

// RoomInfo is the predicate function for roominfo builders.
type RoomInfo func(*sql.Selector)

// RoomStatus is the predicate function for roomstatus builders.
type RoomStatus func(*sql.Selector)

// RoomType is the predicate function for roomtype builders.
type RoomType func(*sql.Selector)
