// Code generated by entc, DO NOT EDIT.

package roomtype

const (
	// Label holds the string label denoting the roomtype type in the database.
	Label = "room_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRoomType holds the string denoting the roomtype field in the database.
	FieldRoomType = "room_type"
	// FieldCost holds the string denoting the cost field in the database.
	FieldCost = "cost"

	// EdgeRoom holds the string denoting the room edge name in mutations.
	EdgeRoom = "room"

	// Table holds the table name of the roomtype in the database.
	Table = "room_types"
	// RoomTable is the table the holds the room relation/edge.
	RoomTable = "rooms"
	// RoomInverseTable is the table name for the Room entity.
	// It exists in this package in order to avoid circular dependency with the "room" package.
	RoomInverseTable = "rooms"
	// RoomColumn is the table column denoting the room relation/edge.
	RoomColumn = "room_type_room"
)

// Columns holds all SQL columns for roomtype fields.
var Columns = []string{
	FieldID,
	FieldRoomType,
	FieldCost,
}
