// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/Asus/app/ent/predicate"
	"github.com/Asus/app/ent/roomtype"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// RoomTypeDelete is the builder for deleting a RoomType entity.
type RoomTypeDelete struct {
	config
	hooks      []Hook
	mutation   *RoomTypeMutation
	predicates []predicate.RoomType
}

// Where adds a new predicate to the delete builder.
func (rtd *RoomTypeDelete) Where(ps ...predicate.RoomType) *RoomTypeDelete {
	rtd.predicates = append(rtd.predicates, ps...)
	return rtd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rtd *RoomTypeDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(rtd.hooks) == 0 {
		affected, err = rtd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoomTypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rtd.mutation = mutation
			affected, err = rtd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(rtd.hooks) - 1; i >= 0; i-- {
			mut = rtd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rtd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (rtd *RoomTypeDelete) ExecX(ctx context.Context) int {
	n, err := rtd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rtd *RoomTypeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: roomtype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: roomtype.FieldID,
			},
		},
	}
	if ps := rtd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, rtd.driver, _spec)
}

// RoomTypeDeleteOne is the builder for deleting a single RoomType entity.
type RoomTypeDeleteOne struct {
	rtd *RoomTypeDelete
}

// Exec executes the deletion query.
func (rtdo *RoomTypeDeleteOne) Exec(ctx context.Context) error {
	n, err := rtdo.rtd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{roomtype.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rtdo *RoomTypeDeleteOne) ExecX(ctx context.Context) {
	rtdo.rtd.ExecX(ctx)
}
