// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/Asus/app/ent/room"
	"github.com/Asus/app/ent/roomstatus"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// RoomStatusCreate is the builder for creating a RoomStatus entity.
type RoomStatusCreate struct {
	config
	mutation *RoomStatusMutation
	hooks    []Hook
}

// SetRoomStatus sets the RoomStatus field.
func (rsc *RoomStatusCreate) SetRoomStatus(s string) *RoomStatusCreate {
	rsc.mutation.SetRoomStatus(s)
	return rsc
}

// AddRoomIDs adds the room edge to Room by ids.
func (rsc *RoomStatusCreate) AddRoomIDs(ids ...int) *RoomStatusCreate {
	rsc.mutation.AddRoomIDs(ids...)
	return rsc
}

// AddRoom adds the room edges to Room.
func (rsc *RoomStatusCreate) AddRoom(r ...*Room) *RoomStatusCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return rsc.AddRoomIDs(ids...)
}

// Mutation returns the RoomStatusMutation object of the builder.
func (rsc *RoomStatusCreate) Mutation() *RoomStatusMutation {
	return rsc.mutation
}

// Save creates the RoomStatus in the database.
func (rsc *RoomStatusCreate) Save(ctx context.Context) (*RoomStatus, error) {
	if _, ok := rsc.mutation.RoomStatus(); !ok {
		return nil, &ValidationError{Name: "RoomStatus", err: errors.New("ent: missing required field \"RoomStatus\"")}
	}
	var (
		err  error
		node *RoomStatus
	)
	if len(rsc.hooks) == 0 {
		node, err = rsc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoomStatusMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rsc.mutation = mutation
			node, err = rsc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(rsc.hooks) - 1; i >= 0; i-- {
			mut = rsc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rsc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (rsc *RoomStatusCreate) SaveX(ctx context.Context) *RoomStatus {
	v, err := rsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (rsc *RoomStatusCreate) sqlSave(ctx context.Context) (*RoomStatus, error) {
	rs, _spec := rsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rsc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	rs.ID = int(id)
	return rs, nil
}

func (rsc *RoomStatusCreate) createSpec() (*RoomStatus, *sqlgraph.CreateSpec) {
	var (
		rs    = &RoomStatus{config: rsc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: roomstatus.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: roomstatus.FieldID,
			},
		}
	)
	if value, ok := rsc.mutation.RoomStatus(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: roomstatus.FieldRoomStatus,
		})
		rs.RoomStatus = value
	}
	if nodes := rsc.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roomstatus.RoomTable,
			Columns: []string{roomstatus.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return rs, _spec
}
