// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/Asus/app/ent/predicate"
	"github.com/Asus/app/ent/room"
	"github.com/Asus/app/ent/roominfo"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// RoomInfoUpdate is the builder for updating RoomInfo entities.
type RoomInfoUpdate struct {
	config
	hooks      []Hook
	mutation   *RoomInfoMutation
	predicates []predicate.RoomInfo
}

// Where adds a new predicate for the builder.
func (riu *RoomInfoUpdate) Where(ps ...predicate.RoomInfo) *RoomInfoUpdate {
	riu.predicates = append(riu.predicates, ps...)
	return riu
}

// SetInfo sets the Info field.
func (riu *RoomInfoUpdate) SetInfo(s string) *RoomInfoUpdate {
	riu.mutation.SetInfo(s)
	return riu
}

// AddRoomIDs adds the room edge to Room by ids.
func (riu *RoomInfoUpdate) AddRoomIDs(ids ...int) *RoomInfoUpdate {
	riu.mutation.AddRoomIDs(ids...)
	return riu
}

// AddRoom adds the room edges to Room.
func (riu *RoomInfoUpdate) AddRoom(r ...*Room) *RoomInfoUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return riu.AddRoomIDs(ids...)
}

// Mutation returns the RoomInfoMutation object of the builder.
func (riu *RoomInfoUpdate) Mutation() *RoomInfoMutation {
	return riu.mutation
}

// RemoveRoomIDs removes the room edge to Room by ids.
func (riu *RoomInfoUpdate) RemoveRoomIDs(ids ...int) *RoomInfoUpdate {
	riu.mutation.RemoveRoomIDs(ids...)
	return riu
}

// RemoveRoom removes room edges to Room.
func (riu *RoomInfoUpdate) RemoveRoom(r ...*Room) *RoomInfoUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return riu.RemoveRoomIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (riu *RoomInfoUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(riu.hooks) == 0 {
		affected, err = riu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoomInfoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			riu.mutation = mutation
			affected, err = riu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(riu.hooks) - 1; i >= 0; i-- {
			mut = riu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, riu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (riu *RoomInfoUpdate) SaveX(ctx context.Context) int {
	affected, err := riu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (riu *RoomInfoUpdate) Exec(ctx context.Context) error {
	_, err := riu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (riu *RoomInfoUpdate) ExecX(ctx context.Context) {
	if err := riu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (riu *RoomInfoUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   roominfo.Table,
			Columns: roominfo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: roominfo.FieldID,
			},
		},
	}
	if ps := riu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := riu.mutation.Info(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: roominfo.FieldInfo,
		})
	}
	if nodes := riu.mutation.RemovedRoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roominfo.RoomTable,
			Columns: []string{roominfo.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := riu.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roominfo.RoomTable,
			Columns: []string{roominfo.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, riu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{roominfo.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// RoomInfoUpdateOne is the builder for updating a single RoomInfo entity.
type RoomInfoUpdateOne struct {
	config
	hooks    []Hook
	mutation *RoomInfoMutation
}

// SetInfo sets the Info field.
func (riuo *RoomInfoUpdateOne) SetInfo(s string) *RoomInfoUpdateOne {
	riuo.mutation.SetInfo(s)
	return riuo
}

// AddRoomIDs adds the room edge to Room by ids.
func (riuo *RoomInfoUpdateOne) AddRoomIDs(ids ...int) *RoomInfoUpdateOne {
	riuo.mutation.AddRoomIDs(ids...)
	return riuo
}

// AddRoom adds the room edges to Room.
func (riuo *RoomInfoUpdateOne) AddRoom(r ...*Room) *RoomInfoUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return riuo.AddRoomIDs(ids...)
}

// Mutation returns the RoomInfoMutation object of the builder.
func (riuo *RoomInfoUpdateOne) Mutation() *RoomInfoMutation {
	return riuo.mutation
}

// RemoveRoomIDs removes the room edge to Room by ids.
func (riuo *RoomInfoUpdateOne) RemoveRoomIDs(ids ...int) *RoomInfoUpdateOne {
	riuo.mutation.RemoveRoomIDs(ids...)
	return riuo
}

// RemoveRoom removes room edges to Room.
func (riuo *RoomInfoUpdateOne) RemoveRoom(r ...*Room) *RoomInfoUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return riuo.RemoveRoomIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (riuo *RoomInfoUpdateOne) Save(ctx context.Context) (*RoomInfo, error) {

	var (
		err  error
		node *RoomInfo
	)
	if len(riuo.hooks) == 0 {
		node, err = riuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoomInfoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			riuo.mutation = mutation
			node, err = riuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(riuo.hooks) - 1; i >= 0; i-- {
			mut = riuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, riuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (riuo *RoomInfoUpdateOne) SaveX(ctx context.Context) *RoomInfo {
	ri, err := riuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return ri
}

// Exec executes the query on the entity.
func (riuo *RoomInfoUpdateOne) Exec(ctx context.Context) error {
	_, err := riuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (riuo *RoomInfoUpdateOne) ExecX(ctx context.Context) {
	if err := riuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (riuo *RoomInfoUpdateOne) sqlSave(ctx context.Context) (ri *RoomInfo, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   roominfo.Table,
			Columns: roominfo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: roominfo.FieldID,
			},
		},
	}
	id, ok := riuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing RoomInfo.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := riuo.mutation.Info(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: roominfo.FieldInfo,
		})
	}
	if nodes := riuo.mutation.RemovedRoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roominfo.RoomTable,
			Columns: []string{roominfo.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := riuo.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roominfo.RoomTable,
			Columns: []string{roominfo.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	ri = &RoomInfo{config: riuo.config}
	_spec.Assign = ri.assignValues
	_spec.ScanValues = ri.scanValues()
	if err = sqlgraph.UpdateNode(ctx, riuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{roominfo.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return ri, nil
}
