// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/Asus/app/ent/room"
	"github.com/Asus/app/ent/roominfo"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// RoomInfoCreate is the builder for creating a RoomInfo entity.
type RoomInfoCreate struct {
	config
	mutation *RoomInfoMutation
	hooks    []Hook
}

// SetInfo sets the Info field.
func (ric *RoomInfoCreate) SetInfo(s string) *RoomInfoCreate {
	ric.mutation.SetInfo(s)
	return ric
}

// AddRoomIDs adds the room edge to Room by ids.
func (ric *RoomInfoCreate) AddRoomIDs(ids ...int) *RoomInfoCreate {
	ric.mutation.AddRoomIDs(ids...)
	return ric
}

// AddRoom adds the room edges to Room.
func (ric *RoomInfoCreate) AddRoom(r ...*Room) *RoomInfoCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ric.AddRoomIDs(ids...)
}

// Mutation returns the RoomInfoMutation object of the builder.
func (ric *RoomInfoCreate) Mutation() *RoomInfoMutation {
	return ric.mutation
}

// Save creates the RoomInfo in the database.
func (ric *RoomInfoCreate) Save(ctx context.Context) (*RoomInfo, error) {
	if _, ok := ric.mutation.Info(); !ok {
		return nil, &ValidationError{Name: "Info", err: errors.New("ent: missing required field \"Info\"")}
	}
	var (
		err  error
		node *RoomInfo
	)
	if len(ric.hooks) == 0 {
		node, err = ric.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoomInfoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ric.mutation = mutation
			node, err = ric.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ric.hooks) - 1; i >= 0; i-- {
			mut = ric.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ric.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ric *RoomInfoCreate) SaveX(ctx context.Context) *RoomInfo {
	v, err := ric.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ric *RoomInfoCreate) sqlSave(ctx context.Context) (*RoomInfo, error) {
	ri, _spec := ric.createSpec()
	if err := sqlgraph.CreateNode(ctx, ric.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	ri.ID = int(id)
	return ri, nil
}

func (ric *RoomInfoCreate) createSpec() (*RoomInfo, *sqlgraph.CreateSpec) {
	var (
		ri    = &RoomInfo{config: ric.config}
		_spec = &sqlgraph.CreateSpec{
			Table: roominfo.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: roominfo.FieldID,
			},
		}
	)
	if value, ok := ric.mutation.Info(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: roominfo.FieldInfo,
		})
		ri.Info = value
	}
	if nodes := ric.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roominfo.RoomTable,
			Columns: []string{roominfo.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return ri, _spec
}
