// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"github.com/Asus/app/ent/predicate"
	"github.com/Asus/app/ent/room"
	"github.com/Asus/app/ent/roominfo"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// RoomInfoQuery is the builder for querying RoomInfo entities.
type RoomInfoQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.RoomInfo
	// eager-loading edges.
	withRoom *RoomQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (riq *RoomInfoQuery) Where(ps ...predicate.RoomInfo) *RoomInfoQuery {
	riq.predicates = append(riq.predicates, ps...)
	return riq
}

// Limit adds a limit step to the query.
func (riq *RoomInfoQuery) Limit(limit int) *RoomInfoQuery {
	riq.limit = &limit
	return riq
}

// Offset adds an offset step to the query.
func (riq *RoomInfoQuery) Offset(offset int) *RoomInfoQuery {
	riq.offset = &offset
	return riq
}

// Order adds an order step to the query.
func (riq *RoomInfoQuery) Order(o ...OrderFunc) *RoomInfoQuery {
	riq.order = append(riq.order, o...)
	return riq
}

// QueryRoom chains the current query on the room edge.
func (riq *RoomInfoQuery) QueryRoom() *RoomQuery {
	query := &RoomQuery{config: riq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := riq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(roominfo.Table, roominfo.FieldID, riq.sqlQuery()),
			sqlgraph.To(room.Table, room.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, roominfo.RoomTable, roominfo.RoomColumn),
		)
		fromU = sqlgraph.SetNeighbors(riq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RoomInfo entity in the query. Returns *NotFoundError when no roominfo was found.
func (riq *RoomInfoQuery) First(ctx context.Context) (*RoomInfo, error) {
	ris, err := riq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(ris) == 0 {
		return nil, &NotFoundError{roominfo.Label}
	}
	return ris[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (riq *RoomInfoQuery) FirstX(ctx context.Context) *RoomInfo {
	ri, err := riq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return ri
}

// FirstID returns the first RoomInfo id in the query. Returns *NotFoundError when no id was found.
func (riq *RoomInfoQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = riq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{roominfo.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (riq *RoomInfoQuery) FirstXID(ctx context.Context) int {
	id, err := riq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only RoomInfo entity in the query, returns an error if not exactly one entity was returned.
func (riq *RoomInfoQuery) Only(ctx context.Context) (*RoomInfo, error) {
	ris, err := riq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(ris) {
	case 1:
		return ris[0], nil
	case 0:
		return nil, &NotFoundError{roominfo.Label}
	default:
		return nil, &NotSingularError{roominfo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (riq *RoomInfoQuery) OnlyX(ctx context.Context) *RoomInfo {
	ri, err := riq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return ri
}

// OnlyID returns the only RoomInfo id in the query, returns an error if not exactly one id was returned.
func (riq *RoomInfoQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = riq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{roominfo.Label}
	default:
		err = &NotSingularError{roominfo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (riq *RoomInfoQuery) OnlyIDX(ctx context.Context) int {
	id, err := riq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RoomInfos.
func (riq *RoomInfoQuery) All(ctx context.Context) ([]*RoomInfo, error) {
	if err := riq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return riq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (riq *RoomInfoQuery) AllX(ctx context.Context) []*RoomInfo {
	ris, err := riq.All(ctx)
	if err != nil {
		panic(err)
	}
	return ris
}

// IDs executes the query and returns a list of RoomInfo ids.
func (riq *RoomInfoQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := riq.Select(roominfo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (riq *RoomInfoQuery) IDsX(ctx context.Context) []int {
	ids, err := riq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (riq *RoomInfoQuery) Count(ctx context.Context) (int, error) {
	if err := riq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return riq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (riq *RoomInfoQuery) CountX(ctx context.Context) int {
	count, err := riq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (riq *RoomInfoQuery) Exist(ctx context.Context) (bool, error) {
	if err := riq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return riq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (riq *RoomInfoQuery) ExistX(ctx context.Context) bool {
	exist, err := riq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (riq *RoomInfoQuery) Clone() *RoomInfoQuery {
	return &RoomInfoQuery{
		config:     riq.config,
		limit:      riq.limit,
		offset:     riq.offset,
		order:      append([]OrderFunc{}, riq.order...),
		unique:     append([]string{}, riq.unique...),
		predicates: append([]predicate.RoomInfo{}, riq.predicates...),
		// clone intermediate query.
		sql:  riq.sql.Clone(),
		path: riq.path,
	}
}

//  WithRoom tells the query-builder to eager-loads the nodes that are connected to
// the "room" edge. The optional arguments used to configure the query builder of the edge.
func (riq *RoomInfoQuery) WithRoom(opts ...func(*RoomQuery)) *RoomInfoQuery {
	query := &RoomQuery{config: riq.config}
	for _, opt := range opts {
		opt(query)
	}
	riq.withRoom = query
	return riq
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Info string `json:"Info,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RoomInfo.Query().
//		GroupBy(roominfo.FieldInfo).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (riq *RoomInfoQuery) GroupBy(field string, fields ...string) *RoomInfoGroupBy {
	group := &RoomInfoGroupBy{config: riq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := riq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return riq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		Info string `json:"Info,omitempty"`
//	}
//
//	client.RoomInfo.Query().
//		Select(roominfo.FieldInfo).
//		Scan(ctx, &v)
//
func (riq *RoomInfoQuery) Select(field string, fields ...string) *RoomInfoSelect {
	selector := &RoomInfoSelect{config: riq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := riq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return riq.sqlQuery(), nil
	}
	return selector
}

func (riq *RoomInfoQuery) prepareQuery(ctx context.Context) error {
	if riq.path != nil {
		prev, err := riq.path(ctx)
		if err != nil {
			return err
		}
		riq.sql = prev
	}
	return nil
}

func (riq *RoomInfoQuery) sqlAll(ctx context.Context) ([]*RoomInfo, error) {
	var (
		nodes       = []*RoomInfo{}
		_spec       = riq.querySpec()
		loadedTypes = [1]bool{
			riq.withRoom != nil,
		}
	)
	_spec.ScanValues = func() []interface{} {
		node := &RoomInfo{config: riq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, riq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := riq.withRoom; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*RoomInfo)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
		}
		query.withFKs = true
		query.Where(predicate.Room(func(s *sql.Selector) {
			s.Where(sql.InValues(roominfo.RoomColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.room_info_room
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "room_info_room" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "room_info_room" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.Room = append(node.Edges.Room, n)
		}
	}

	return nodes, nil
}

func (riq *RoomInfoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := riq.querySpec()
	return sqlgraph.CountNodes(ctx, riq.driver, _spec)
}

func (riq *RoomInfoQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := riq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (riq *RoomInfoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   roominfo.Table,
			Columns: roominfo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: roominfo.FieldID,
			},
		},
		From:   riq.sql,
		Unique: true,
	}
	if ps := riq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := riq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := riq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := riq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (riq *RoomInfoQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(riq.driver.Dialect())
	t1 := builder.Table(roominfo.Table)
	selector := builder.Select(t1.Columns(roominfo.Columns...)...).From(t1)
	if riq.sql != nil {
		selector = riq.sql
		selector.Select(selector.Columns(roominfo.Columns...)...)
	}
	for _, p := range riq.predicates {
		p(selector)
	}
	for _, p := range riq.order {
		p(selector)
	}
	if offset := riq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := riq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RoomInfoGroupBy is the builder for group-by RoomInfo entities.
type RoomInfoGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rigb *RoomInfoGroupBy) Aggregate(fns ...AggregateFunc) *RoomInfoGroupBy {
	rigb.fns = append(rigb.fns, fns...)
	return rigb
}

// Scan applies the group-by query and scan the result into the given value.
func (rigb *RoomInfoGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := rigb.path(ctx)
	if err != nil {
		return err
	}
	rigb.sql = query
	return rigb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (rigb *RoomInfoGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := rigb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (rigb *RoomInfoGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(rigb.fields) > 1 {
		return nil, errors.New("ent: RoomInfoGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := rigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (rigb *RoomInfoGroupBy) StringsX(ctx context.Context) []string {
	v, err := rigb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (rigb *RoomInfoGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = rigb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{roominfo.Label}
	default:
		err = fmt.Errorf("ent: RoomInfoGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (rigb *RoomInfoGroupBy) StringX(ctx context.Context) string {
	v, err := rigb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (rigb *RoomInfoGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(rigb.fields) > 1 {
		return nil, errors.New("ent: RoomInfoGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := rigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (rigb *RoomInfoGroupBy) IntsX(ctx context.Context) []int {
	v, err := rigb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (rigb *RoomInfoGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = rigb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{roominfo.Label}
	default:
		err = fmt.Errorf("ent: RoomInfoGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (rigb *RoomInfoGroupBy) IntX(ctx context.Context) int {
	v, err := rigb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (rigb *RoomInfoGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(rigb.fields) > 1 {
		return nil, errors.New("ent: RoomInfoGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := rigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (rigb *RoomInfoGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := rigb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (rigb *RoomInfoGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = rigb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{roominfo.Label}
	default:
		err = fmt.Errorf("ent: RoomInfoGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (rigb *RoomInfoGroupBy) Float64X(ctx context.Context) float64 {
	v, err := rigb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (rigb *RoomInfoGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(rigb.fields) > 1 {
		return nil, errors.New("ent: RoomInfoGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := rigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (rigb *RoomInfoGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := rigb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (rigb *RoomInfoGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = rigb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{roominfo.Label}
	default:
		err = fmt.Errorf("ent: RoomInfoGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (rigb *RoomInfoGroupBy) BoolX(ctx context.Context) bool {
	v, err := rigb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (rigb *RoomInfoGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := rigb.sqlQuery().Query()
	if err := rigb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (rigb *RoomInfoGroupBy) sqlQuery() *sql.Selector {
	selector := rigb.sql
	columns := make([]string, 0, len(rigb.fields)+len(rigb.fns))
	columns = append(columns, rigb.fields...)
	for _, fn := range rigb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(rigb.fields...)
}

// RoomInfoSelect is the builder for select fields of RoomInfo entities.
type RoomInfoSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (ris *RoomInfoSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := ris.path(ctx)
	if err != nil {
		return err
	}
	ris.sql = query
	return ris.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ris *RoomInfoSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ris.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (ris *RoomInfoSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ris.fields) > 1 {
		return nil, errors.New("ent: RoomInfoSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ris.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ris *RoomInfoSelect) StringsX(ctx context.Context) []string {
	v, err := ris.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (ris *RoomInfoSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ris.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{roominfo.Label}
	default:
		err = fmt.Errorf("ent: RoomInfoSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ris *RoomInfoSelect) StringX(ctx context.Context) string {
	v, err := ris.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (ris *RoomInfoSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ris.fields) > 1 {
		return nil, errors.New("ent: RoomInfoSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ris.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ris *RoomInfoSelect) IntsX(ctx context.Context) []int {
	v, err := ris.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (ris *RoomInfoSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ris.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{roominfo.Label}
	default:
		err = fmt.Errorf("ent: RoomInfoSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ris *RoomInfoSelect) IntX(ctx context.Context) int {
	v, err := ris.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (ris *RoomInfoSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ris.fields) > 1 {
		return nil, errors.New("ent: RoomInfoSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ris.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ris *RoomInfoSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ris.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (ris *RoomInfoSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ris.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{roominfo.Label}
	default:
		err = fmt.Errorf("ent: RoomInfoSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ris *RoomInfoSelect) Float64X(ctx context.Context) float64 {
	v, err := ris.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (ris *RoomInfoSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ris.fields) > 1 {
		return nil, errors.New("ent: RoomInfoSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ris.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ris *RoomInfoSelect) BoolsX(ctx context.Context) []bool {
	v, err := ris.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (ris *RoomInfoSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ris.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{roominfo.Label}
	default:
		err = fmt.Errorf("ent: RoomInfoSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ris *RoomInfoSelect) BoolX(ctx context.Context) bool {
	v, err := ris.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ris *RoomInfoSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ris.sqlQuery().Query()
	if err := ris.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ris *RoomInfoSelect) sqlQuery() sql.Querier {
	selector := ris.sql
	selector.Select(selector.Columns(ris.fields...)...)
	return selector
}
