// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/Asus/app/ent/predicate"
	"github.com/Asus/app/ent/room"
	"github.com/Asus/app/ent/roominfo"
	"github.com/Asus/app/ent/roomstatus"
	"github.com/Asus/app/ent/roomtype"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// RoomUpdate is the builder for updating Room entities.
type RoomUpdate struct {
	config
	hooks      []Hook
	mutation   *RoomMutation
	predicates []predicate.Room
}

// Where adds a new predicate for the builder.
func (ru *RoomUpdate) Where(ps ...predicate.Room) *RoomUpdate {
	ru.predicates = append(ru.predicates, ps...)
	return ru
}

// SetRoomstatusID sets the roomstatus edge to RoomStatus by id.
func (ru *RoomUpdate) SetRoomstatusID(id int) *RoomUpdate {
	ru.mutation.SetRoomstatusID(id)
	return ru
}

// SetNillableRoomstatusID sets the roomstatus edge to RoomStatus by id if the given value is not nil.
func (ru *RoomUpdate) SetNillableRoomstatusID(id *int) *RoomUpdate {
	if id != nil {
		ru = ru.SetRoomstatusID(*id)
	}
	return ru
}

// SetRoomstatus sets the roomstatus edge to RoomStatus.
func (ru *RoomUpdate) SetRoomstatus(r *RoomStatus) *RoomUpdate {
	return ru.SetRoomstatusID(r.ID)
}

// SetRoomtypeID sets the roomtype edge to RoomType by id.
func (ru *RoomUpdate) SetRoomtypeID(id int) *RoomUpdate {
	ru.mutation.SetRoomtypeID(id)
	return ru
}

// SetNillableRoomtypeID sets the roomtype edge to RoomType by id if the given value is not nil.
func (ru *RoomUpdate) SetNillableRoomtypeID(id *int) *RoomUpdate {
	if id != nil {
		ru = ru.SetRoomtypeID(*id)
	}
	return ru
}

// SetRoomtype sets the roomtype edge to RoomType.
func (ru *RoomUpdate) SetRoomtype(r *RoomType) *RoomUpdate {
	return ru.SetRoomtypeID(r.ID)
}

// SetRoominfoID sets the roominfo edge to RoomInfo by id.
func (ru *RoomUpdate) SetRoominfoID(id int) *RoomUpdate {
	ru.mutation.SetRoominfoID(id)
	return ru
}

// SetNillableRoominfoID sets the roominfo edge to RoomInfo by id if the given value is not nil.
func (ru *RoomUpdate) SetNillableRoominfoID(id *int) *RoomUpdate {
	if id != nil {
		ru = ru.SetRoominfoID(*id)
	}
	return ru
}

// SetRoominfo sets the roominfo edge to RoomInfo.
func (ru *RoomUpdate) SetRoominfo(r *RoomInfo) *RoomUpdate {
	return ru.SetRoominfoID(r.ID)
}

// Mutation returns the RoomMutation object of the builder.
func (ru *RoomUpdate) Mutation() *RoomMutation {
	return ru.mutation
}

// ClearRoomstatus clears the roomstatus edge to RoomStatus.
func (ru *RoomUpdate) ClearRoomstatus() *RoomUpdate {
	ru.mutation.ClearRoomstatus()
	return ru
}

// ClearRoomtype clears the roomtype edge to RoomType.
func (ru *RoomUpdate) ClearRoomtype() *RoomUpdate {
	ru.mutation.ClearRoomtype()
	return ru
}

// ClearRoominfo clears the roominfo edge to RoomInfo.
func (ru *RoomUpdate) ClearRoominfo() *RoomUpdate {
	ru.mutation.ClearRoominfo()
	return ru
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (ru *RoomUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(ru.hooks) == 0 {
		affected, err = ru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoomMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ru.mutation = mutation
			affected, err = ru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ru.hooks) - 1; i >= 0; i-- {
			mut = ru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RoomUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RoomUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RoomUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ru *RoomUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   room.Table,
			Columns: room.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: room.FieldID,
			},
		},
	}
	if ps := ru.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if ru.mutation.RoomstatusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoomstatusTable,
			Columns: []string{room.RoomstatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomstatus.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RoomstatusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoomstatusTable,
			Columns: []string{room.RoomstatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomstatus.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ru.mutation.RoomtypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoomtypeTable,
			Columns: []string{room.RoomtypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomtype.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RoomtypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoomtypeTable,
			Columns: []string{room.RoomtypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomtype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ru.mutation.RoominfoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoominfoTable,
			Columns: []string{room.RoominfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roominfo.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RoominfoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoominfoTable,
			Columns: []string{room.RoominfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roominfo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{room.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// RoomUpdateOne is the builder for updating a single Room entity.
type RoomUpdateOne struct {
	config
	hooks    []Hook
	mutation *RoomMutation
}

// SetRoomstatusID sets the roomstatus edge to RoomStatus by id.
func (ruo *RoomUpdateOne) SetRoomstatusID(id int) *RoomUpdateOne {
	ruo.mutation.SetRoomstatusID(id)
	return ruo
}

// SetNillableRoomstatusID sets the roomstatus edge to RoomStatus by id if the given value is not nil.
func (ruo *RoomUpdateOne) SetNillableRoomstatusID(id *int) *RoomUpdateOne {
	if id != nil {
		ruo = ruo.SetRoomstatusID(*id)
	}
	return ruo
}

// SetRoomstatus sets the roomstatus edge to RoomStatus.
func (ruo *RoomUpdateOne) SetRoomstatus(r *RoomStatus) *RoomUpdateOne {
	return ruo.SetRoomstatusID(r.ID)
}

// SetRoomtypeID sets the roomtype edge to RoomType by id.
func (ruo *RoomUpdateOne) SetRoomtypeID(id int) *RoomUpdateOne {
	ruo.mutation.SetRoomtypeID(id)
	return ruo
}

// SetNillableRoomtypeID sets the roomtype edge to RoomType by id if the given value is not nil.
func (ruo *RoomUpdateOne) SetNillableRoomtypeID(id *int) *RoomUpdateOne {
	if id != nil {
		ruo = ruo.SetRoomtypeID(*id)
	}
	return ruo
}

// SetRoomtype sets the roomtype edge to RoomType.
func (ruo *RoomUpdateOne) SetRoomtype(r *RoomType) *RoomUpdateOne {
	return ruo.SetRoomtypeID(r.ID)
}

// SetRoominfoID sets the roominfo edge to RoomInfo by id.
func (ruo *RoomUpdateOne) SetRoominfoID(id int) *RoomUpdateOne {
	ruo.mutation.SetRoominfoID(id)
	return ruo
}

// SetNillableRoominfoID sets the roominfo edge to RoomInfo by id if the given value is not nil.
func (ruo *RoomUpdateOne) SetNillableRoominfoID(id *int) *RoomUpdateOne {
	if id != nil {
		ruo = ruo.SetRoominfoID(*id)
	}
	return ruo
}

// SetRoominfo sets the roominfo edge to RoomInfo.
func (ruo *RoomUpdateOne) SetRoominfo(r *RoomInfo) *RoomUpdateOne {
	return ruo.SetRoominfoID(r.ID)
}

// Mutation returns the RoomMutation object of the builder.
func (ruo *RoomUpdateOne) Mutation() *RoomMutation {
	return ruo.mutation
}

// ClearRoomstatus clears the roomstatus edge to RoomStatus.
func (ruo *RoomUpdateOne) ClearRoomstatus() *RoomUpdateOne {
	ruo.mutation.ClearRoomstatus()
	return ruo
}

// ClearRoomtype clears the roomtype edge to RoomType.
func (ruo *RoomUpdateOne) ClearRoomtype() *RoomUpdateOne {
	ruo.mutation.ClearRoomtype()
	return ruo
}

// ClearRoominfo clears the roominfo edge to RoomInfo.
func (ruo *RoomUpdateOne) ClearRoominfo() *RoomUpdateOne {
	ruo.mutation.ClearRoominfo()
	return ruo
}

// Save executes the query and returns the updated entity.
func (ruo *RoomUpdateOne) Save(ctx context.Context) (*Room, error) {

	var (
		err  error
		node *Room
	)
	if len(ruo.hooks) == 0 {
		node, err = ruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoomMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ruo.mutation = mutation
			node, err = ruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ruo.hooks) - 1; i >= 0; i-- {
			mut = ruo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ruo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RoomUpdateOne) SaveX(ctx context.Context) *Room {
	r, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return r
}

// Exec executes the query on the entity.
func (ruo *RoomUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RoomUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ruo *RoomUpdateOne) sqlSave(ctx context.Context) (r *Room, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   room.Table,
			Columns: room.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: room.FieldID,
			},
		},
	}
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Room.ID for update")}
	}
	_spec.Node.ID.Value = id
	if ruo.mutation.RoomstatusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoomstatusTable,
			Columns: []string{room.RoomstatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomstatus.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RoomstatusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoomstatusTable,
			Columns: []string{room.RoomstatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomstatus.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ruo.mutation.RoomtypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoomtypeTable,
			Columns: []string{room.RoomtypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomtype.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RoomtypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoomtypeTable,
			Columns: []string{room.RoomtypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomtype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ruo.mutation.RoominfoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoominfoTable,
			Columns: []string{room.RoominfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roominfo.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RoominfoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoominfoTable,
			Columns: []string{room.RoominfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roominfo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	r = &Room{config: ruo.config}
	_spec.Assign = r.assignValues
	_spec.ScanValues = r.scanValues()
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{room.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return r, nil
}
