// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/Asus/app/ent/predicate"
	"github.com/Asus/app/ent/roominfo"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// RoomInfoDelete is the builder for deleting a RoomInfo entity.
type RoomInfoDelete struct {
	config
	hooks      []Hook
	mutation   *RoomInfoMutation
	predicates []predicate.RoomInfo
}

// Where adds a new predicate to the delete builder.
func (rid *RoomInfoDelete) Where(ps ...predicate.RoomInfo) *RoomInfoDelete {
	rid.predicates = append(rid.predicates, ps...)
	return rid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rid *RoomInfoDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(rid.hooks) == 0 {
		affected, err = rid.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoomInfoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rid.mutation = mutation
			affected, err = rid.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(rid.hooks) - 1; i >= 0; i-- {
			mut = rid.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rid.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (rid *RoomInfoDelete) ExecX(ctx context.Context) int {
	n, err := rid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rid *RoomInfoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: roominfo.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: roominfo.FieldID,
			},
		},
	}
	if ps := rid.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, rid.driver, _spec)
}

// RoomInfoDeleteOne is the builder for deleting a single RoomInfo entity.
type RoomInfoDeleteOne struct {
	rid *RoomInfoDelete
}

// Exec executes the deletion query.
func (rido *RoomInfoDeleteOne) Exec(ctx context.Context) error {
	n, err := rido.rid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{roominfo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rido *RoomInfoDeleteOne) ExecX(ctx context.Context) {
	rido.rid.ExecX(ctx)
}
