// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// RoomsColumns holds the columns for the "rooms" table.
	RoomsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "room_info_room", Type: field.TypeInt, Nullable: true},
		{Name: "room_status_room", Type: field.TypeInt, Nullable: true},
		{Name: "room_type_room", Type: field.TypeInt, Nullable: true},
	}
	// RoomsTable holds the schema information for the "rooms" table.
	RoomsTable = &schema.Table{
		Name:       "rooms",
		Columns:    RoomsColumns,
		PrimaryKey: []*schema.Column{RoomsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "rooms_room_infos_room",
				Columns: []*schema.Column{RoomsColumns[1]},

				RefColumns: []*schema.Column{RoomInfosColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "rooms_room_status_room",
				Columns: []*schema.Column{RoomsColumns[2]},

				RefColumns: []*schema.Column{RoomStatusColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "rooms_room_types_room",
				Columns: []*schema.Column{RoomsColumns[3]},

				RefColumns: []*schema.Column{RoomTypesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// RoomInfosColumns holds the columns for the "room_infos" table.
	RoomInfosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "info", Type: field.TypeString},
	}
	// RoomInfosTable holds the schema information for the "room_infos" table.
	RoomInfosTable = &schema.Table{
		Name:        "room_infos",
		Columns:     RoomInfosColumns,
		PrimaryKey:  []*schema.Column{RoomInfosColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// RoomStatusColumns holds the columns for the "room_status" table.
	RoomStatusColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "room_status", Type: field.TypeString},
	}
	// RoomStatusTable holds the schema information for the "room_status" table.
	RoomStatusTable = &schema.Table{
		Name:        "room_status",
		Columns:     RoomStatusColumns,
		PrimaryKey:  []*schema.Column{RoomStatusColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// RoomTypesColumns holds the columns for the "room_types" table.
	RoomTypesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "room_type", Type: field.TypeString},
		{Name: "cost", Type: field.TypeInt},
	}
	// RoomTypesTable holds the schema information for the "room_types" table.
	RoomTypesTable = &schema.Table{
		Name:        "room_types",
		Columns:     RoomTypesColumns,
		PrimaryKey:  []*schema.Column{RoomTypesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RoomsTable,
		RoomInfosTable,
		RoomStatusTable,
		RoomTypesTable,
	}
)

func init() {
	RoomsTable.ForeignKeys[0].RefTable = RoomInfosTable
	RoomsTable.ForeignKeys[1].RefTable = RoomStatusTable
	RoomsTable.ForeignKeys[2].RefTable = RoomTypesTable
}
