/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersRoom
 */
export interface ControllersRoom {
    /**
     * 
     * @type {number}
     * @memberof ControllersRoom
     */
    roomInfo?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersRoom
     */
    roomStatus?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersRoom
     */
    roomType?: number;
}

export function ControllersRoomFromJSON(json: any): ControllersRoom {
    return ControllersRoomFromJSONTyped(json, false);
}

export function ControllersRoomFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersRoom {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'roomInfo': !exists(json, 'Roominfo') ? undefined : json['Roominfo'],
        'roomStatus': !exists(json, 'Roomstatus') ? undefined : json['Roomstatus'],
        'roomType': !exists(json, 'Roomtype') ? undefined : json['Roomtype'],
    };
}

export function ControllersRoomToJSON(value?: ControllersRoom | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'roomInfo': value.roomInfo,
        'roomStatus': value.roomStatus,
        'roomType': value.roomType,
    };
}


