/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRoomStatusEdges,
    EntRoomStatusEdgesFromJSON,
    EntRoomStatusEdgesFromJSONTyped,
    EntRoomStatusEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRoomStatus
 */
export interface EntRoomStatus {
    /**
     * RoomStatus holds the value of the "RoomStatus" field.
     * @type {string}
     * @memberof EntRoomStatus
     */
    roomStatus?: string;
    /**
     * 
     * @type {EntRoomStatusEdges}
     * @memberof EntRoomStatus
     */
    edges?: EntRoomStatusEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntRoomStatus
     */
    id?: number;
}

export function EntRoomStatusFromJSON(json: any): EntRoomStatus {
    return EntRoomStatusFromJSONTyped(json, false);
}

export function EntRoomStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRoomStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'roomStatus': !exists(json, 'RoomStatus') ? undefined : json['RoomStatus'],
        'edges': !exists(json, 'edges') ? undefined : EntRoomStatusEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntRoomStatusToJSON(value?: EntRoomStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'RoomStatus': value.roomStatus,
        'edges': EntRoomStatusEdgesToJSON(value.edges),
        'id': value.id,
    };
}


