/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRoomInfo,
    EntRoomInfoFromJSON,
    EntRoomInfoFromJSONTyped,
    EntRoomInfoToJSON,
    EntRoomStatus,
    EntRoomStatusFromJSON,
    EntRoomStatusFromJSONTyped,
    EntRoomStatusToJSON,
    EntRoomType,
    EntRoomTypeFromJSON,
    EntRoomTypeFromJSONTyped,
    EntRoomTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRoomEdges
 */
export interface EntRoomEdges {
    /**
     * 
     * @type {EntRoomInfo}
     * @memberof EntRoomEdges
     */
    roominfo?: EntRoomInfo;
    /**
     * 
     * @type {EntRoomStatus}
     * @memberof EntRoomEdges
     */
    roomstatus?: EntRoomStatus;
    /**
     * 
     * @type {EntRoomType}
     * @memberof EntRoomEdges
     */
    roomtype?: EntRoomType;
}

export function EntRoomEdgesFromJSON(json: any): EntRoomEdges {
    return EntRoomEdgesFromJSONTyped(json, false);
}

export function EntRoomEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRoomEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'roominfo': !exists(json, 'Roominfo') ? undefined : EntRoomInfoFromJSON(json['Roominfo']),
        'roomstatus': !exists(json, 'Roomstatus') ? undefined : EntRoomStatusFromJSON(json['Roomstatus']),
        'roomtype': !exists(json, 'Roomtype') ? undefined : EntRoomTypeFromJSON(json['Roomtype']),
    };
}

export function EntRoomEdgesToJSON(value?: EntRoomEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'roominfo': EntRoomInfoToJSON(value.roominfo),
        'roomstatus': EntRoomStatusToJSON(value.roomstatus),
        'roomtype': EntRoomTypeToJSON(value.roomtype),
    };
}


