/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRoomInfoEdges,
    EntRoomInfoEdgesFromJSON,
    EntRoomInfoEdgesFromJSONTyped,
    EntRoomInfoEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRoomInfo
 */
export interface EntRoomInfo {
    /**
     * Info holds the value of the "Info" field.
     * @type {string}
     * @memberof EntRoomInfo
     */
    info?: string;
    /**
     * 
     * @type {EntRoomInfoEdges}
     * @memberof EntRoomInfo
     */
    edges?: EntRoomInfoEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntRoomInfo
     */
    id?: number;
}

export function EntRoomInfoFromJSON(json: any): EntRoomInfo {
    return EntRoomInfoFromJSONTyped(json, false);
}

export function EntRoomInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRoomInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'info': !exists(json, 'Info') ? undefined : json['Info'],
        'edges': !exists(json, 'edges') ? undefined : EntRoomInfoEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntRoomInfoToJSON(value?: EntRoomInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Info': value.info,
        'edges': EntRoomInfoEdgesToJSON(value.edges),
        'id': value.id,
    };
}


