/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRoomTypeEdges,
    EntRoomTypeEdgesFromJSON,
    EntRoomTypeEdgesFromJSONTyped,
    EntRoomTypeEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRoomType
 */
export interface EntRoomType {
    /**
     * Cost holds the value of the "Cost" field.
     * @type {number}
     * @memberof EntRoomType
     */
    cost?: number;
    /**
     * RoomType holds the value of the "RoomType" field.
     * @type {string}
     * @memberof EntRoomType
     */
    roomType?: string;
    /**
     * 
     * @type {EntRoomTypeEdges}
     * @memberof EntRoomType
     */
    edges?: EntRoomTypeEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntRoomType
     */
    id?: number;
}

export function EntRoomTypeFromJSON(json: any): EntRoomType {
    return EntRoomTypeFromJSONTyped(json, false);
}

export function EntRoomTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRoomType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cost': !exists(json, 'Cost') ? undefined : json['Cost'],
        'roomType': !exists(json, 'RoomType') ? undefined : json['RoomType'],
        'edges': !exists(json, 'edges') ? undefined : EntRoomTypeEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntRoomTypeToJSON(value?: EntRoomType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Cost': value.cost,
        'RoomType': value.roomType,
        'edges': EntRoomTypeEdgesToJSON(value.edges),
        'id': value.id,
    };
}


