// Code generated by entc, DO NOT EDIT.

package room

const (
	// Label holds the string label denoting the room type in the database.
	Label = "room"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// EdgeRoomstatus holds the string denoting the roomstatus edge name in mutations.
	EdgeRoomstatus = "roomstatus"
	// EdgeRoomtype holds the string denoting the roomtype edge name in mutations.
	EdgeRoomtype = "roomtype"
	// EdgeRoominfo holds the string denoting the roominfo edge name in mutations.
	EdgeRoominfo = "roominfo"

	// Table holds the table name of the room in the database.
	Table = "rooms"
	// RoomstatusTable is the table the holds the roomstatus relation/edge.
	RoomstatusTable = "rooms"
	// RoomstatusInverseTable is the table name for the RoomStatus entity.
	// It exists in this package in order to avoid circular dependency with the "roomstatus" package.
	RoomstatusInverseTable = "room_status"
	// RoomstatusColumn is the table column denoting the roomstatus relation/edge.
	RoomstatusColumn = "room_status_room"
	// RoomtypeTable is the table the holds the roomtype relation/edge.
	RoomtypeTable = "rooms"
	// RoomtypeInverseTable is the table name for the RoomType entity.
	// It exists in this package in order to avoid circular dependency with the "roomtype" package.
	RoomtypeInverseTable = "room_types"
	// RoomtypeColumn is the table column denoting the roomtype relation/edge.
	RoomtypeColumn = "room_type_room"
	// RoominfoTable is the table the holds the roominfo relation/edge.
	RoominfoTable = "rooms"
	// RoominfoInverseTable is the table name for the RoomInfo entity.
	// It exists in this package in order to avoid circular dependency with the "roominfo" package.
	RoominfoInverseTable = "room_infos"
	// RoominfoColumn is the table column denoting the roominfo relation/edge.
	RoominfoColumn = "room_info_room"
)

// Columns holds all SQL columns for room fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Room type.
var ForeignKeys = []string{
	"room_info_room",
	"room_status_room",
	"room_type_room",
}
