// Code generated by entc, DO NOT EDIT.

package roomstatus

const (
	// Label holds the string label denoting the roomstatus type in the database.
	Label = "room_status"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRoomStatus holds the string denoting the roomstatus field in the database.
	FieldRoomStatus = "room_status"

	// EdgeRoom holds the string denoting the room edge name in mutations.
	EdgeRoom = "room"

	// Table holds the table name of the roomstatus in the database.
	Table = "room_status"
	// RoomTable is the table the holds the room relation/edge.
	RoomTable = "rooms"
	// RoomInverseTable is the table name for the Room entity.
	// It exists in this package in order to avoid circular dependency with the "room" package.
	RoomInverseTable = "rooms"
	// RoomColumn is the table column denoting the room relation/edge.
	RoomColumn = "room_status_room"
)

// Columns holds all SQL columns for roomstatus fields.
var Columns = []string{
	FieldID,
	FieldRoomStatus,
}
